name: shorebird_redis_client
description: A lightweight Dart client library for communicating with a Redis server. Built by Shorebird.
version: 0.0.12
homepage: https://shorebird.dev
repository: https://github.com/shorebirdtech/shorebird/tree/main/packages/redis_client
topics: [redis, cache, shorebird]
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  resp_client: ^1.2.0

dev_dependencies:
  test: ^1.29.0
