name: flutter_version_resolver
description: A CLI app that determines whether 
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  mason_logger: ^0.3.3
  path: ^1.9.1
  pub_semver: ^2.2.0
  scoped_deps: ^0.1.0+2
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.24.0
