$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  ["coverage", "bin/cache", "third_party", "build", "*.xcscheme", "fixtures"]
words:
  - ANDROIDD
  - Apks
  - Azul
  - Entra
  - FLUSHALL
  - LOCALAPPDATA
  - NOAUTH
  - Oltman
  - PRNG
  - RSAPKCS
  - Retryable
  - SIGSTOP
  - USERPROFILE
  - Unpatchable
  - VCRUNTIME
  - Verdana
  - WRONGPASS
  - aabs
  - aapt
  - aarch
  - aars # Android Archive
  - allprojects # From gradle files
  - altool
  - apigee
  - appbundle
  - archs
  - armeabi
  - backboardd
  - bintools
  - bitcode
  - bryanoltman
  - bundletool
  - canvaskit
  - carryforward
  - cipd
  - codesign
  - codesigned
  - codesigning
  - deflavored
  - devicectl
  - dorny # From .github dir, doesn't show up in "**" check?
  - dyld
  - dylib
  - endtemplate
  - exitcode
  - exportoptions
  - felangel
  - genhtml
  - gradlew
  - hotreload
  - idevicesyslog
  - iokit
  - iphoneos
  - lerping
  - libapp
  - libflutter
  - libimobiledevice
  - libplist
  - lldb
  - logcat
  - longpaths
  - lproj
  - metadatas
  - mktemp
  - mocktail
  - multioption
  - noaudio # From .github dir, doesn't show up in "**" check?
  - nserror
  - orri # Arm64 instruction, Or Register with Immediate
  - pana
  - pkcs
  - podfile
  - podspec
  - pointycastle
  - precache
  - previewable
  - propertylistserialization
  - propertylistserialization
  - pubspec
  - pwsh
  - reactivecircus # From .github dir, doesn't show up in "**" check?
  - readlink
  - reinit
  - requirepass # From .github dir, doesn't show up in "**" check?
  - shorebirdtech
  - sideload
  - sideloadable
  - sideloaded
  - signup
  - storyboardc
  - subosito # From .github dir, doesn't show up in "**" check?
  - swiftshader # From .github dir, doesn't show up in "**" check?
  - sysroot
  - temurin # From .github dir, doesn't show up in "**" check?
  - udid # Unique Device Identifier
  - unawaited
  - unmockable
  - unsets
  - upvote
  - usbmuxd
  - vmcode
  - writeln
  - xcarchive
  - xcarchives
  - xcframework
  - xcodebuild
  - xcodeproj
  - xcrun
  - xcscheme
  - xcschemes
  - xcshareddata
  - xcworkspace
  - xlink
