name: _
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - packages/artifact_proxy
  - packages/discord_gcp_alerts
  - packages/flutter_version_resolver
  - packages/jwt
  - packages/redis_client
  - packages/scoped_deps
  - packages/shorebird_cli
  - packages/shorebird_code_push_client
  - packages/shorebird_code_push_protocol
  - packages/stripe_api

dev_dependencies:
  very_good_analysis: ^9.0.0
