name: shorebird_code_push_protocol
description: Library which contains common interfaces used by Shorebird CodePush
version: 0.1.0+1
repository: https://github.com/shorebirdtech/shorebird
resolution: workspace

publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  decimal: ^3.2.4
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.8.0
  json_serializable: ^6.11.0
  mocktail: ^1.0.0
  test: ^1.26.3
