name: jwt
description: A Dart Json Web Token Library
version: 1.0.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  clock: ^1.1.0
  collection: ^1.18.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  meta: ^1.7.0
  pointycastle: ^4.0.0
  rsa_pkcs: ^2.0.0
  ttl_cache: ^0.3.0

dev_dependencies:
  build_runner: ^2.6.1
  json_serializable: ^6.1.4
  path: ^1.9.0
  test: ^1.26.3
