name: artifact_proxy
description: Intercept and proxy Flutter artifact requests.
version: 1.0.0
repository: https://github.com/shorebirdtech/shorebird/
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  checked_yaml: ^2.0.2
  collection: ^1.17.1
  http: ^0.13.5
  json_annotation: ^4.8.0
  quiver: ^3.2.1
  shelf: ^1.4.0
  shelf_hotreload: ^1.4.0

dev_dependencies:
  build_runner: ^2.0.0  
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
