name: artifact_proxy
description: Intercept and proxy Flutter artifact requests.
version: 1.0.0
repository: https://github.com/shorebirdtech/shorebird/
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  checked_yaml: ^2.0.2
  collection: ^1.19.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  quiver: ^3.2.2
  shelf: ^1.4.2
  shelf_hotreload: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^8.0.0
