name: shorebird_cli
description: Command-line tool to interact with Shorebird's services.
version: 0.14.10
repository: https://github.com/shorebirdtech/shorebird

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.3.6
  args: ^2.3.1
  barbecue: ^0.4.0
  checked_yaml: ^2.0.2
  cli_completion: ^0.3.0
  cli_util: ^0.4.0
  collection: ^1.17.1
  crypto: ^3.0.2
  googleapis_auth: ^1.4.0
  http: ^1.0.0
  intl: ^0.18.0
  io: ^1.0.4
  json_annotation: ^4.8.0
  mason_logger: ^0.2.9
  meta: ^1.9.0
  path: ^1.8.3
  platform: ^3.1.0
  propertylistserialization: ^1.3.0
  pubspec_parse: ^1.2.2
  scoped:
    path: ../scoped
  shorebird_code_push_client:
    path: ../shorebird_code_push_client
  uuid: ^3.0.7
  version: ^3.0.2
  xml: ^6.2.2
  yaml: ^3.1.1
  yaml_edit: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  json_serializable: ^6.6.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

executables:
  shorebird:
