name: shorebird_cli
description: Command-line tool to interact with Shorebird's services.
version: 1.6.72
repository: https://github.com/shorebirdtech/shorebird
resolution: workspace

publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  archive: ^4.0.7
  args: ^2.7.0
  checked_yaml: ^2.0.4
  cli_completion: ^0.5.0
  cli_util: ^0.4.2
  clock: ^1.1.2
  collection: ^1.19.1
  crypto: ^3.0.6
  equatable: ^2.0.7
  googleapis_auth: ^2.0.0
  http: ^1.5.0
  intl: ^0.20.2
  io: ^1.0.5
  json_annotation: ^4.9.0
  json_path: ^0.8.0
  jwt:
    path: ../jwt
  mason_logger: ^0.3.0
  meta: ^1.16.0
  path: ^1.9.1
  pem: ^2.0.5
  platform: ^3.1.6
  pointycastle: ^4.0.0
  propertylistserialization: ^1.4.1
  pub_semver: ^2.2.0
  pubspec_parse: ^1.5.0
  retry: ^3.1.2
  scoped_deps: ^0.1.0
  shorebird_code_push_client:
    path: ../shorebird_code_push_client
  shorebird_code_push_protocol:
    path: ../shorebird_code_push_protocol
  stream_transform: ^2.1.1
  uuid: ^4.5.1
  xml: ^6.5.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  build_runner: ^2.10.1
  build_verify: ^3.1.1
  build_version: ^2.1.1
  json_serializable: ^6.11.0
  mocktail: ^1.0.3
  test: ^1.26.3

executables:
  shorebird:
