name: shorebird_cli
description: Command-line tool to interact with Shorebird's services.
version: 1.0.6
repository: https://github.com/shorebirdtech/shorebird

publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:  
  archive: ^3.5.1
  args: ^2.5.0
  barbecue: ^0.5.0
  checked_yaml: ^2.0.3
  cli_completion: ^0.5.0
  cli_util: ^0.4.1
  collection: ^1.18.0
  crypto: ^3.0.3
  googleapis_auth: ^1.6.0
  http: ^1.2.1
  intl: ^0.19.0
  io: ^1.0.4
  json_annotation: ^4.9.0
  json_path: ^0.7.1
  jwt:
    path: ../jwt
  mason_logger: ^0.2.15
  meta: ^1.14.0
  path: ^1.9.0
  platform: ^3.1.4
  propertylistserialization: ^1.3.0
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  scoped:
    path: ../scoped
  shorebird_code_push_client:
    path: ../shorebird_code_push_client
  shorebird_code_push_protocol:
    path: ../shorebird_code_push_protocol
  uuid: ^4.4.0
  xml: ^6.5.0
  yaml: ^3.1.2
  yaml_edit: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.9
  build_verify: ^3.1.0
  build_version: ^2.1.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.4
  very_good_analysis: ^5.1.0

executables:
  shorebird:
