name: shorebird_code_push_client
description: Library which allows Dart applications to interact with the Shorebird CodePush API
version: 0.9.0+1
repository: https://github.com/shorebirdtech/shorebird

publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  http: ^1.0.0
  path: ^1.9.0
  shorebird_code_push_protocol:
    path: ../shorebird_code_push_protocol

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^7.0.0
