name: discord_gcp_alerts
description: A server which proxies GCP Alert notifications to Discord.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.0.0
  json_annotation: ^4.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^5.0.0
