name: discord_gcp_alerts
description: A server which proxies GCP Alert notifications to Discord.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.0.0
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  test: ^1.25.14
  very_good_analysis: ^7.0.0
