name: scoped_deps
description: A simple Dart library for managing scoped dependencies built on top of Zones from dart:async.
version: 0.1.0+2
homepage: https://shorebird.dev
repository: https://github.com/shorebirdtech/shorebird/tree/main/packages/scoped_deps
resolution: workspace

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.29.0
