name: scoped_deps
description: A simple Dart library for managing scoped dependencies built on top of Zones from dart:async.
version: 0.1.0+1
homepage: https://shorebird.dev
repository: https://github.com/shorebirdtech/shorebird/tree/main/packages/scoped_deps

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.0.0
  very_good_analysis: ^5.1.0
