name: cutler
description: A tool for managing Flutter forks.
version: 1.0.0
repository: https://github.com/shorebirdtech/shorebird
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^5.1.0

dependencies:
  args: ^2.4.0
  collection: ^1.18.0
  io: ^1.0.4
  mason_logger: ^0.2.6
  meta: ^1.9.1
  mocktail: ^1.0.0
  path: ^1.8.3
  scoped:
    path: ../scoped
