name: nightly_e2e

on:
  # For testing
  pull_request:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  verify_cli_installation:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Verify Shorebird Installation
        run: |
          if ./bin/shorebird --version | grep -q '^Shorebird \d\.\d\.\d$'; then
            echo 'âœ… Shorebird CLI is installed!'
          else
            echo 'âŒ Shorebird CLI is not installed.'
          exit 1
          fi
